#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND "0x15"
#define DISTRHO_PLUGIN_NAME  "FractalSoundExplorer Plugin"
#define DISTRHO_PLUGIN_URI   "https://github.com/0x0015/FractalSoundExplorer-VST"

#define DISTRHO_PLUGIN_HAS_UI        1
#define DISTRHO_PLUGIN_IS_RT_SAFE    1
#define DISTRHO_PLUGIN_NUM_INPUTS    0
#define DISTRHO_PLUGIN_NUM_OUTPUTS   2
#define DISTRHO_PLUGIN_WANT_PROGRAMS 1
#define DISTRHO_PLUGIN_IS_SYNTH      0

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
